name: Cilium CLI tests

permissions:
  contents: read
  actions: read

on:
  pull_request:
    paths-ignore:
      - 'Documentation/**'
      - 'test/**'
  workflow_dispatch:
    inputs:
      fastci:
        type: boolean
        required: false
        default: false

jobs:
  build-cilium-cli-binaries:
    name: Build Cilium CLI binaries
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: FastCI
        if: inputs.fastci == 'true'
        uses: jfrog-fastci/fastci@main
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          fastci_otel_token: ${{ vars.FASTCI_TOKEN }}

      - name: Setup go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          cache: false
          # renovate: datasource=golang-version depName=go
          go-version: 1.24.6

      - name: Load Golang cache build from GitHub
        uses: actions/cache/restore@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        id: go-cache
        with:
          path: /tmp/.cache/go
          key: ${{ runner.os }}-go-cilium-cli-cache-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-cilium-cli-cache-

      - name: Create cache directories if they don't exist
        if: ${{ steps.go-cache.outputs.cache-hit != 'true' }}
        shell: bash
        run: |
          mkdir -p /tmp/.cache/go/.cache/go-build
          mkdir -p /tmp/.cache/go/pkg

      - name: Build Cilium CLI release binaries
        env:
          GOCACHE: "/tmp/.cache/go/.cache/go-build"
          GOMODCACHE: "/tmp/.cache/go/pkg"
        run: |
          make -C cilium-cli local-release
